#!/bin/bash
set -e

jshint immunity_notifications/static/immunity-notifications/js/*.js
stylelint "immunity_notifications/static/immunity-notifications/css/*.css"

immunity-qa-check \
        --csslinter \
        --jslinter \
        --migration-path "./immunity_notifications/migrations/" \
        --migration-module "immunity_notifications"

echo ''
echo 'Running checks for SAMPLE_APP'
SAMPLE_APP=1 immunity-qa-check \
    --skip-isort \
    --skip-flake8 \
    --skip-checkmigrations \
    --skip-checkendline \
    --skip-checkcommit \
    --skip-black \
    --migration-path "./tests/immunity2/sample_notifications/migrations/" \
    --migration-module "sample_notifications"
